# Generated by Django 4.2.13 on 2026-01-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='function_manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='functional_head',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
